kind: Deployment
apiVersion: apps/v1
metadata:
  name: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      creationTimestamp: null
      labels:
        purpose: troubleshooting
        app: toolbox
    spec:
      containers:
        - name: toolbox
          image: <repository_url>/toolbox:latest
          command:
            - /bin/sleep
            - infinite
          imagePullPolicy: Always
      restartPolicy: Always